### ISSUE TITLE
He.BottomBar - Adding child with position directly on ui fails

### ISSUE THREAD

**Issue by lainsce** [tau-OS/libhelium#11]
### What Happened?

When you add a child using typing to set its position, like below, it fails.

```
<child>
  <object class="HeBottomBar">
    <property name="collapse_actions">0</property>
    <child type="left">
      <object class="HeIconicButton" />
    </child>
  </object>
</child>
 ```

### Steps to Reproduce

When you try to add a child, it fails, so have to add childs directly.

### Expected Behavior

Should be able to add children to a bottombar using typing without fail.

### OS Version

1.x (Martin Perl)

### Software Version

Compiled from git

### Log Output

```shell
N/A
```

### Hardware Info

N/A

**Comment by lleyton** [comment]
fixed
