### ISSUE TITLE
He.BottomBar - Have to explicitly say collapse_actions is false

### ISSUE THREAD

**Issue by lainsce** [tau-OS/libhelium#12]
### What Happened?

When you add a He.BottomBar, nothing shows on either side when not using it inside a He.Album, and that's because one has to explicitly say collapse_actions is false for items to appear.

### Steps to Reproduce

Add a He.BottomBar to your app, with actions on either side

See that none show up, because it's expecting collapse_actions to be either true or false from somewhere.

### Expected Behavior

The widget shoudl default to showing actions if not inside a He.Album

### OS Version

1.x (Martin Perl)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

N/A

**Comment by lleyton** [comment]
in the latest release the bottombar seems to be defaulting to expanded

might be worth it to add a "responsive" mode for auto collapsing based on width, although that has it's own issues

will close for now, but we want to add something like a auto mode, we may continue this issue
