### ISSUE TITLE
AboutWindow has no close button

### ISSUE THREAD

**Issue by korewaChino** [tau-OS/libhelium#42]
### What Happened?

AboutWindow has no close button
![image](https://github.com/tau-OS/libhelium/assets/38139192/e163a77e-25bb-4d8d-8178-298fd2d26f91)

### Steps to Reproduce

Use AboutWindow

### Expected Behavior

AboutWindow has an `x` button to close it

### OS Version

Ultramarine Linux

### Software Version

Latest release (I have run all updates)

**Comment by lainsce** [comment]
Fixed in latest release.
